import type { PlatformConfig } from "./types.js";

export const LINKEDIN_PLATFORM: PlatformConfig = {
  source: "linkedin",
  hostPattern: /(?:^|\.)linkedin\.(?:com|cn)$/i,
  listCard: ".jobs-search-results__list-item, .job-card-container, li.scaffold-layout__list-item",
  listActionTargets: [".job-card-container__content", ".job-card-list__entity-lockup", ".job-card-container"],
  listTitle: [".base-search-card__title", ".job-card-list__title", "h3"],
  listCompany: [".base-search-card__subtitle", ".job-card-container__company-name", ".artdeco-entity-lockup__subtitle"],
  listSalary: [".salary", ".compensation__salary"],
  listLocation: [".job-search-card__location", ".job-card-container__metadata-item"],
  listLink: [
    "a.base-card__full-link",
    "a.job-card-list__title",
    "a[href*='/jobs/view/']",
    "a[href*='/incareer/jobs/view/']",
  ],
  listTags: [".job-card-container__metadata-wrapper li", ".job-card-container__footer-item"],
  listCompanyTags: [".job-card-container__metadata-item", ".job-card-container__insight"],
  detailTitle: [".job-details-jobs-unified-top-card__job-title", "h1.t-24", "h1"],
  detailCompany: [".job-details-jobs-unified-top-card__company-name", ".jobs-unified-top-card__company-name"],
  detailSalary: [".salary", ".compensation__salary"],
  detailLocation: [".job-details-jobs-unified-top-card__bullet", ".jobs-unified-top-card__bullet"],
  detailDescription: [
    ".jobs-description-content__text",
    ".jobs-description__content",
    ".jobs-box__html-content",
    ".show-more-less-html__markup",
    "[class*='description__text']",
    "[class*='jobs-description']",
  ],
  detailApplyLink: ["a.jobs-apply-button", "a[data-control-name='jobdetails_topcard_inapply']"],
  detailPostedAt: [
    ".jobs-unified-top-card__tertiary-description-container .tvm__text",
    ".job-details-jobs-unified-top-card__tertiary-description-container .tvm__text",
  ],
  detailTags: [".job-details-preferences-and-skills__pill", ".job-details-how-you-match__skills-item-subtitle"],
  detailCompanyTags: [".jobs-company__box li", ".jobs-company__inline-information li"],
  detailPathHint: /(?:jobs\/view|incareer\/jobs\/view)/i,
};
