import type { PlatformConfig } from "./types.js";

export const SHIXISENG_PLATFORM: PlatformConfig = {
  source: "shixiseng",
  hostPattern: /(?:^|\.)shixiseng\.com$/i,
  listCard: ".intern-item, .position-item, .intern-wrap .intern-item",
  listActionTargets: [".intern-detail", ".intern-item__bd", ".position-item"],
  listTitle: [".job-name", ".name", ".title a"],
  listCompany: [".company-name", ".company-info .name", ".company"],
  listSalary: [".day-salary", ".salary"],
  listLocation: [".area", ".city", ".address"],
  listLink: ["a[href*='/intern/']", "a"],
  listTags: [".more span", ".job-tags span"],
  listCompanyTags: [".company-more span", ".company-tags span"],
  detailTitle: [".new_job_name", ".job-name", "h1"],
  detailCompany: [".com-name", ".company-name", ".company-info .name"],
  detailSalary: [".job_money", ".salary"],
  detailLocation: [".job_position", ".position", ".city"],
  detailDescription: [
    ".intern_position_detail",
    ".job_part .job_detail .intern-from-api",
    ".job_detail .intern-from-api",
    ".job_detail",
    ".detail-content",
    ".job-desc",
    "[class*='position_detail']",
    "[class*='job_detail']",
  ],
  detailApplyLink: ["a.apply-btn", "a[href*='delivery']"],
  detailPostedAt: [".job_publish_time", ".publish_time", ".job_msg .cutom_font", ".job_msg span"],
  detailTags: [".job_msg span", ".job-tags span"],
  detailCompanyTags: [".com_msg span", ".company-tags span"],
  detailPathHint: /\/intern\/[^/?#]+/i,
};
